### ISSUE TITLE
[BUG] : Problem Page's Navbar's title opening new tab

### ISSUE THREAD

**Issue by rajdeep010v2** [rajdeep010v2/Practice-Repo#1]
**About the Issue**
When we are clicking on the problem page's navbar heading it is openning a new page.

**How to create the issue**
1. Open the problem.html page on browser.
2. Click the "Saviour 75" heading attached to the navbar.
3. It is opening a new tab.

![Screenshot Capture - 2023-11-05 - 22-20-17](https://github.com/rajdeep010v2/Practice-Repo/assets/149956835/b677506d-185b-4e7d-a995-82b59ce69189)

**Comment by krishnaa-14** [comment]
I will like to work on this, Can you assign this to me.
